name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or master, depending on your default branch name

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure Next.js for static export
        run: |
          # Create or update next.config.js for static export
          cat > next.config.js << EOL
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            reactStrictMode: true,
            swcMinify: true,
            images: {
              domains: [],
              unoptimized: true,
            },
            output: 'export',
            basePath: '/hempnotyx',
            assetPrefix: '/hempnotyx/',
            trailingSlash: true,
          };

          module.exports = nextConfig;
          EOL

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Add .nojekyll file
        run: touch out/.nojekyll

      - name: Copy assets to correct paths
        run: |
          # Ensure public files are correctly copied
          mkdir -p out/hempnotyx
          if [ -d "public" ]; then
            cp -r public/* out/hempnotyx/ || true
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true 